from scrapy.item import Item, Field

class NycGovParksEventItem(Item):
    source = Field()
    source_url = Field()
    schema_version = Field()

    event_guid = Field()
    event_id = Field()
    _id = Field()

    start_timestamp = Field()
    end_timestamp = Field()
    date_str = Field()
    time_str = Field()
    is_canceled = Field()
    nycgovparks_url = Field()
    is_all_day = Field()
    name = Field()
    description = Field()
    description_short = Field()
    info_email = Field()
    event_url = Field()
    contact_name = Field()
    contact_phone = Field()
    location_name = Field()
    location_address_type = Field()
    location_address = Field()
    location_city = Field()
    location_state = Field()
    location_zip = Field()
    location_boroughs = Field()
    location_map_type = Field()
    location_geometry = Field()

    gcal_url = Field()
    ical_url = Field()
    event_alert = Field()
    location_lat = Field()
    location_lng = Field()
    location_locality = Field()
    price_range = Field()
    organizer = Field()
    organizer_url = Field()
    contact_email = Field()
    related_urls = Field()
    categories = Field()
    event_links = Field()


